export const onegodianMembersPlugin = {
  name: 'OneGodian Members',
  slug: 'onegodian-members',
  version: '2.2.0',
  packageName: 'onegodian-members-v2.2.0-production.zip',
  canonicalRepository: 'ohi-stack/onegodian-platform-plugin',
  canonicalBranch: 'main',
  wordpressBaseUrl: 'https://onegodian.org',
  dashboardUrl: 'https://onegodian.org/members/',
  membershipsUrl: 'https://onegodian.org/product-category/memberships/',
  myAccountUrl: 'https://onegodian.org/my-account/',
  appRoute: '/members',
  status: 'production-candidate-sync',
  hposCompatible: true,
  woocommerceProductSync: true,
  stripeFallbackMode: 'woocommerce-product-links',
  managedPages: [
    '/member-dashboard/',
    '/member-profile/',
    '/onegodian-ally/',
    '/belief-mapper/',
    '/onegodian-journey/',
    '/onegodian-time/',
    '/onegodian-date-converter/',
  ],
  membersApi: {
    namespace: 'onegodian/v1',
    memberSummary: '/wp-json/onegodian/v1/members/me',
    mapper: '/wp-json/onegodian/v1/members/belief-mapper',
    currentTime: '/wp-json/onegodian/v1/time/current',
    timeConvert: '/wp-json/onegodian/v1/time/convert',
    bridgeStatus: 'wordpress-runtime-authority',
  },
  mapper: {
    questionSlots: 7,
    questionsDefaultEmpty: true,
    journeyStages: ['Seeker', 'Believer', 'OneGodian', 'Elder'],
    autoStageAssignment: false,
    rawAnswersPrivateByDefault: true,
    publicStageOptIn: true,
  },
  otsV5: {
    epochGregorian: '2025-03-18',
    epochOneGodian: 'Genesis 01, 0000 OT',
    monthCount: 13,
    month10: 'Covenant',
    gregorianSourceOfRecord: true,
  },
  shortcodes: [
    '[onegodian_member_dashboard]',
    '[onegodian_member_profile]',
    '[onegodian_ally_status]',
    '[onegodian_belief_mapper]',
    '[onegodian_journey_center]',
    '[onegodian_journey_passport]',
    '[onegodian_daily_question]',
    '[onegodian_purpose_compass]',
    '[onegodian_current_date]',
    '[onegodian_dual_date]',
    '[onegodian_time_dashboard]',
    '[onegodian_date_converter]',
    '[onegodian_calendar]',
  ],
  membershipLevels: [
    'Spiritual',
    'Tribal',
    'Business',
    'Digital Real Estate',
    'Pet',
    'Student',
    'Senior',
  ],
  billingModes: ['Monthly', 'Annual'],
  brand: {
    obsidian: '#070607',
    panel: '#17121f',
    purple: '#6f3cff',
    gold: '#d8b35a',
    goldLight: '#f0d98a',
    softWhite: '#f5f1e8',
  },
} as const;

export type OnegodianMembersPluginConfig = typeof onegodianMembersPlugin;
