export const onegodianMembersPlugin = {
  name: 'OneGodian Members',
  slug: 'onegodian-members',
  version: '2.3.0',
  packageName: 'onegodian-members-v2.3.0-production.zip',
  canonicalRepository: 'ohi-stack/onegodian-platform-plugin',
  canonicalBranch: 'main',
  wordpressBaseUrl: 'https://onegodian.org',
  dashboardUrl: 'https://onegodian.org/member-dashboard/',
  profileUrl: 'https://onegodian.org/member-profile/',
  communityDirectoryUrl: 'https://onegodian.org/members/',
  membershipsUrl: 'https://onegodian.org/product-category/memberships/',
  myAccountUrl: 'https://onegodian.org/my-account/',
  createAccountUrl: 'https://onegodian.org/my-account/',
  lostPasswordUrl: 'https://onegodian.org/my-account/lost-password/',
  beliefMapperUrl: 'https://onegodian.org/belief-mapper/',
  journeyUrl: 'https://onegodian.org/onegodian-journey/',
  onegodian101Url: 'https://onegodian.org/onegodian-101/',
  onegodian101ProgressUrl: 'https://onegodian.org/onegodian-101-progress/',
  onegodianTimeUrl: 'https://onegodian.org/onegodian-time/',
  dateConverterUrl: 'https://onegodian.org/onegodian-date-converter/',
  appRoute: '/members',
  status: 'production-candidate-sync',
  credentialAuthority: 'wordpress-woocommerce',
  hposCompatible: true,
  woocommerceProductSync: true,
  stripeFallbackMode: 'woocommerce-product-links',
  managedPages: [
    '/member-dashboard/',
    '/member-profile/',
    '/membership/',
    '/onegodian-ally/',
    '/belief-mapper/',
    '/onegodian-journey/',
    '/onegodian-101/',
    '/onegodian-101-progress/',
    '/onegodian-time/',
    '/onegodian-date-converter/',
    '/member-resources/',
    '/member-certificate/',
    '/member-id/',
    '/community/',
    '/members/',
    '/groups/',
    '/member-messages/',
    '/member-notifications/',
    '/member-support/',
    '/my-account/',
    '/affiliate-dashboard/',
    '/creator-network/',
    '/contributors/',
  ],
  membersApi: {
    namespace: 'onegodian/v1',
    memberSummary: '/wp-json/onegodian/v1/members/me',
    onegodian101Progress: '/wp-json/onegodian/v1/members/me/onegodian-101',
    onegodian101Lessons: '/wp-json/onegodian/v1/onegodian-101/lessons',
    onegodian101Terms: '/wp-json/onegodian/v1/onegodian-101/terms',
    mapper: '/wp-json/onegodian/v1/members/belief-mapper',
    currentTime: '/wp-json/onegodian/v1/time/current',
    timeConvert: '/wp-json/onegodian/v1/time/convert',
    bridgeStatus: 'wordpress-runtime-authority',
  },
  mapper: {
    questionSlots: 7,
    questionsDefaultEmpty: true,
    journeyStages: ['Seeker', 'Believer', 'OneGodian', 'Elder'],
    autoStageAssignment: false,
    rawAnswersPrivateByDefault: true,
    publicStageOptIn: true,
  },
  otsV5: {
    epochGregorian: '2025-03-18',
    epochOneGodian: 'Genesis 01, 0000 OT',
    monthCount: 13,
    month10: 'Covenant',
    gregorianSourceOfRecord: true,
  },
  shortcodes: [
    '[onegodian_member_dashboard]',
    '[onegodian_member_profile]',
    '[onegodian_members_pricing]',
    '[onegodian_ally_status]',
    '[onegodian_belief_mapper]',
    '[onegodian_belief_status]',
    '[onegodian_belief_progress]',
    '[onegodian_journey_stage]',
    '[onegodian_identity_reflection]',
    '[onegodian_journey_center]',
    '[onegodian_journey_passport]',
    '[onegodian_daily_question]',
    '[onegodian_purpose_compass]',
    '[onegodian_101]',
    '[onegodian_101_lessons]',
    '[onegodian_101_lesson]',
    '[onegodian_101_progress]',
    '[onegodian_101_next_steps]',
    '[onegodian_101_terms]',
    '[onegodian_101_ecosystem_map]',
    '[onegodian_101_resume]',
    '[onegodian_current_date]',
    '[onegodian_dual_date]',
    '[onegodian_time_dashboard]',
    '[onegodian_date_converter]',
    '[onegodian_calendar]',
    '[onegodian_member_date]',
  ],
  legacyShortcodes: ['[onegodian_members_dashboard]'],
  membershipLevels: [
    'Spiritual',
    'Tribal',
    'Business',
    'Digital Real Estate',
    'Pet',
    'Student',
    'Senior',
  ],
  billingModes: ['Monthly', 'Annual'],
  brand: {
    obsidian: '#070607',
    panel: '#17121f',
    purple: '#6f3cff',
    gold: '#d8b35a',
    goldLight: '#f0d98a',
    softWhite: '#f5f1e8',
  },
} as const;

export type OnegodianMembersPluginConfig = typeof onegodianMembersPlugin;
